import sqlite3
import pandas as pd

현대건설기계필드클레임_2022 = pd.read_excel('X:/ComeSys_QMS/db/현대건설기계 2022년 필드 클레임 정리.xlsx')
수입검사현황_2023 = pd.read_excel('X:/ComeSys_QMS/db/2023년 수입검사일일현황.xlsx')
공정검사현황_2023 = pd.read_excel('X:/ComeSys_QMS/db/2023년 공정검사일일현황.xlsx')
출하검사현황_2023 = pd.read_excel('X:/ComeSys_QMS/db/2023년 출하검사일일현황.xlsx')
인라인부적합현황_2023 = pd.read_excel('X:/ComeSys_QMS/db/2023년 인라인 부적합 현황.xlsx')
고객불만품질비용_2023 = pd.read_excel('X:/ComeSys_QMS/db/2023년 고객불만_품질비용 현황.xlsx')
JCB필드클레임_2023 = pd.read_excel('X:/ComeSys_QMS/db/JCB 2023년 필드 클레임 정리.xlsx')
대동필드클레임_2023 = pd.read_excel('X:/ComeSys_QMS/db/대동 2023년 필드 클레임 정리.xlsx')
클라크필드클레임_2023 = pd.read_excel('X:/ComeSys_QMS/db/클라크 2023년 필드 클레임 정리.xlsx')
현대건설기계필드클레임_2023 = pd.read_excel('X:/ComeSys_QMS/db/현대건설기계 2023년 필드 클레임 정리.xlsx')
클레임비용현황_2023 = pd.read_excel('X:/ComeSys_QMS/db/2023년 클레임비용 현황.xlsx')
부품단가리스트 = pd.read_excel('X:/ComeSys_QMS/db/부품단가리스트.xlsx')
곤산_고품관리 = pd.read_excel('X:/ComeSys_QMS/db/고품관리_곤산.xlsx')
곤산_클레임비용현황 = pd.read_excel('X:/ComeSys_QMS/db/클레임비용현황_곤산.xlsx')
곤산_수입검사현황 = pd.read_excel('X:/ComeSys_QMS/db/수입검사일일현황_곤산.xlsx')
곤산_공정검사현황 = pd.read_excel('X:/ComeSys_QMS/db/공정검사일일현황_곤산.xlsx')
곤산_출하검사현황 = pd.read_excel('X:/ComeSys_QMS/db/출하검사일일현황_곤산.xlsx')

conn = sqlite3.connect("X:/ComeSys_QMS/db/qms.db")
conn1 = sqlite3.connect("X:/ComeSys_QMS/db/qms_kunshan.db")

현대건설기계필드클레임_2022.to_sql('현대건설기계필드클레임_2022',conn,if_exists='replace')
print('TASK1 OK')
수입검사현황_2023.to_sql('수입검사현황_2023',conn,if_exists='replace')
print('TASK2 OK')
공정검사현황_2023.to_sql('공정검사현황_2023',conn,if_exists='replace')
print('TASK3 OK')
출하검사현황_2023.to_sql('출하검사현황_2023',conn,if_exists='replace')
print('TASK4 OK')
인라인부적합현황_2023.to_sql('인라인부적합현황_2023',conn,if_exists='replace')
print('TASK5 OK')
고객불만품질비용_2023.to_sql('고객불만품질비용_2023',conn,if_exists='replace')
print('TASK6 OK')
JCB필드클레임_2023.to_sql('JCB필드클레임_2023',conn,if_exists='replace')
print('TASK7 OK')
대동필드클레임_2023.to_sql('대동필드클레임_2023',conn,if_exists='replace')
print('TASK8 OK')
클라크필드클레임_2023.to_sql('클라크필드클레임_2023',conn,if_exists='replace')
print('TASK9 OK')
현대건설기계필드클레임_2023.to_sql('현대건설기계필드클레임_2023',conn,if_exists='replace')
print('TASK10 OK')
클레임비용현황_2023.to_sql('클레임비용현황_2023',conn,if_exists='replace')
print('TASK11 OK')
부품단가리스트.to_sql('부품단가리스트',conn,if_exists='replace')
print('TASK12 OK')
곤산_고품관리.to_sql('곤산_고품관리',conn1,if_exists='replace')
print('TASK13 OK')
곤산_클레임비용현황.to_sql('곤산_클레임비용현황',conn1,if_exists='replace')
print('TASK14 OK')
곤산_수입검사현황.to_sql('곤산_수입검사현황',conn1,if_exists='replace')
print('TASK15 OK')
곤산_공정검사현황.to_sql('곤산_공정검사현황',conn1,if_exists='replace')
print('TASK16 OK')
곤산_출하검사현황.to_sql('곤산_출하검사현황',conn1,if_exists='replace')
print('TASK17 OK')

cur = conn.cursor()
cur1 = conn1.cursor()
conn.commit()
conn1.commit()
conn.close()
conn1.close()
